"""remove phone number

Revision ID: 515e6154818b
Revises: c096e09e32e6
Create Date: 2026-02-14 20:33:26.429533

"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "515e6154818b"
down_revision: str | None = "c096e09e32e6"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "phone_number")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column(
            "phone_number",
            sa.VARCHAR(length=20),
            autoincrement=False,
            nullable=False,
        ),
    )
    # ### end Alembic commands ###
