"""add bot_events and funnels

Revision ID: 8897832f8a8d
Revises: b7d3e9f1a2c4
Create Date: 2026-08-31 12:10:49.003247

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "8897832f8a8d"
down_revision: Union[str, None] = "b7d3e9f1a2c4"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "funnels",
        sa.Column("bot_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("steps", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("window_seconds", sa.Integer(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["bot_id"], ["bots.id"], name=op.f("fk_funnels_bot_id_bots")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_funnels")),
    )
    op.create_index("ix_funnels_bot_id", "funnels", ["bot_id"], unique=False)
    op.create_index(
        op.f("ix_funnels_is_deleted"), "funnels", ["is_deleted"], unique=False
    )
    op.create_table(
        "bot_events",
        sa.Column("bot_id", sa.UUID(), nullable=False),
        sa.Column("telegram_user_id", sa.UUID(), nullable=True),
        sa.Column("tg_user_id", sa.BigInteger(), nullable=False),
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.Column("props", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("ts", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["bot_id"], ["bots.id"], name=op.f("fk_bot_events_bot_id_bots")
        ),
        sa.ForeignKeyConstraint(
            ["telegram_user_id"],
            ["telegram_users.id"],
            name=op.f("fk_bot_events_telegram_user_id_telegram_users"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_bot_events")),
    )
    op.create_index(
        "ix_bot_events_bot_name_ts",
        "bot_events",
        ["bot_id", "name", "ts"],
        unique=False,
    )
    op.create_index(
        "ix_bot_events_bot_user_ts",
        "bot_events",
        ["bot_id", "telegram_user_id", "ts"],
        unique=False,
    )
    op.create_index(
        "ix_bot_events_funnel",
        "bot_events",
        ["bot_id", "tg_user_id", "name", "ts", "id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_bot_events_funnel", table_name="bot_events")
    op.drop_index("ix_bot_events_bot_user_ts", table_name="bot_events")
    op.drop_index("ix_bot_events_bot_name_ts", table_name="bot_events")
    op.drop_table("bot_events")
    op.drop_index(op.f("ix_funnels_is_deleted"), table_name="funnels")
    op.drop_index("ix_funnels_bot_id", table_name="funnels")
    op.drop_table("funnels")
    # ### end Alembic commands ###
