"""initial

Revision ID: 9a0e3f8c57e6
Revises:
Create Date: 2026-01-04 17:02:13.889587

"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "9a0e3f8c57e6"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum("OWNER", "MEMBER", name="workspacerole").create(op.get_bind())
    sa.Enum("PENDING", "SUCCESS", "FAILED", "SKIPPED", name="deliverystatus").create(
        op.get_bind()
    )
    sa.Enum(
        "DRAFT",
        "SCHEDULED",
        "PROCESSING",
        "SENT",
        "FAILED",
        "CANCELLED",
        name="broadcaststatus",
    ).create(op.get_bind())
    sa.Enum(
        "TEXT",
        "MEDIA",
        "IMAGE",
        "VIDEO",
        "AUDIO",
        "DOCUMENT",
        "SYSTEM",
        name="messagetype",
    ).create(op.get_bind())
    sa.Enum("USER", "BOT", "ADMIN", "SYSTEM", name="sendertype").create(op.get_bind())
    sa.Enum("OPEN", "CLOSED", "BLOCKED", name="chatstatus").create(op.get_bind())
    sa.Enum("ADMIN", "EDITOR", "SUPPORT", "VIEWER", name="botrole").create(
        op.get_bind()
    )
    sa.Enum("ACTIVE", "DISABLED", "MAINTENANCE", name="botstatus").create(op.get_bind())
    op.create_table(
        "users",
        sa.Column("first_name", sa.String(length=50), nullable=False),
        sa.Column("last_name", sa.String(length=50), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("username", sa.String(length=60), nullable=False),
        sa.Column("phone_number", sa.String(length=20), nullable=False),
        sa.Column("password", sa.String(length=255), nullable=False),
        sa.Column("is_superuser", sa.Boolean(), nullable=False),
        sa.Column("is_verified", sa.Boolean(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
    )
    op.create_index(op.f("ix_users_is_deleted"), "users", ["is_deleted"], unique=False)
    op.create_index(
        "uq_users_email_active_not_deleted",
        "users",
        ["email"],
        unique=True,
        postgresql_where=sa.text("is_deleted = false"),
    )
    op.create_index(
        "uq_users_username_not_deleted",
        "users",
        ["username"],
        unique=True,
        postgresql_where=sa.text("is_deleted = false"),
    )
    op.create_table(
        "workspaces",
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_workspaces")),
    )
    op.create_table(
        "bots",
        sa.Column("workspace_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("username", sa.String(length=100), nullable=False),
        sa.Column("token_hash", sa.String(length=255), nullable=False),
        sa.Column("token_encrypted", sa.String(length=1000), nullable=False),
        sa.Column(
            "status",
            postgresql.ENUM(
                "ACTIVE",
                "DISABLED",
                "MAINTENANCE",
                name="botstatus",
                create_type=False,
            ),
            nullable=False,
        ),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.id"],
            name=op.f("fk_bots_workspace_id_workspaces"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_bots")),
        sa.UniqueConstraint("username", name=op.f("uq_bots_username")),
    )
    op.create_index(op.f("ix_bots_is_deleted"), "bots", ["is_deleted"], unique=False)
    op.create_table(
        "workspace_members",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("workspace_id", sa.UUID(), nullable=False),
        sa.Column(
            "role",
            postgresql.ENUM("OWNER", "MEMBER", name="workspacerole", create_type=False),
            nullable=False,
        ),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_workspace_members_user_id_users"),
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.id"],
            name=op.f("fk_workspace_members_workspace_id_workspaces"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_workspace_members")),
        sa.UniqueConstraint("user_id", "workspace_id", name="uq_workspace_member"),
    )
    op.create_table(
        "admin_bot_roles",
        sa.Column("admin_id", sa.UUID(), nullable=False),
        sa.Column("bot_id", sa.UUID(), nullable=False),
        sa.Column(
            "role",
            postgresql.ENUM(
                "ADMIN",
                "EDITOR",
                "SUPPORT",
                "VIEWER",
                name="botrole",
                create_type=False,
            ),
            nullable=False,
        ),
        sa.Column(
            "permissions",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=False,
        ),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["admin_id"],
            ["users.id"],
            name=op.f("fk_admin_bot_roles_admin_id_users"),
        ),
        sa.ForeignKeyConstraint(
            ["bot_id"],
            ["bots.id"],
            name=op.f("fk_admin_bot_roles_bot_id_bots"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_admin_bot_roles")),
        sa.UniqueConstraint("admin_id", "bot_id", name="uq_admin_bot_role"),
    )
    op.create_table(
        "audit_logs",
        sa.Column("admin_id", sa.UUID(), nullable=False),
        sa.Column("bot_id", sa.UUID(), nullable=True),
        sa.Column("action_type", sa.String(length=100), nullable=False),
        sa.Column("target_entity", sa.String(length=100), nullable=False),
        sa.Column("target_id", sa.String(length=100), nullable=True),
        sa.Column("details", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["admin_id"],
            ["users.id"],
            name=op.f("fk_audit_logs_admin_id_users"),
        ),
        sa.ForeignKeyConstraint(
            ["bot_id"], ["bots.id"], name=op.f("fk_audit_logs_bot_id_bots")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_audit_logs")),
    )
    op.create_table(
        "broadcasts",
        sa.Column("bot_id", sa.UUID(), nullable=False),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.Column("message_content", sa.Text(), nullable=False),
        sa.Column("filters", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "status",
            postgresql.ENUM(
                "DRAFT",
                "SCHEDULED",
                "PROCESSING",
                "SENT",
                "FAILED",
                "CANCELLED",
                name="broadcaststatus",
                create_type=False,
            ),
            nullable=False,
        ),
        sa.Column("scheduled_at", sa.DateTime(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["bot_id"], ["bots.id"], name=op.f("fk_broadcasts_bot_id_bots")
        ),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
            name=op.f("fk_broadcasts_created_by_users"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_broadcasts")),
    )
    op.create_index(
        op.f("ix_broadcasts_is_deleted"),
        "broadcasts",
        ["is_deleted"],
        unique=False,
    )
    op.create_table(
        "telegram_users",
        sa.Column("tg_user_id", sa.BigInteger(), nullable=False),
        sa.Column("bot_id", sa.UUID(), nullable=False),
        sa.Column("first_name", sa.String(length=255), nullable=True),
        sa.Column("username", sa.String(length=255), nullable=True),
        sa.Column("language_code", sa.String(length=10), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["bot_id"], ["bots.id"], name=op.f("fk_telegram_users_bot_id_bots")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_telegram_users")),
        sa.UniqueConstraint("tg_user_id", "bot_id", name="uq_tg_user_bot"),
    )
    op.create_index(
        "idx_tg_user_bot",
        "telegram_users",
        ["tg_user_id", "bot_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_telegram_users_is_deleted"),
        "telegram_users",
        ["is_deleted"],
        unique=False,
    )
    op.create_table(
        "broadcast_deliveries",
        sa.Column("broadcast_id", sa.UUID(), nullable=False),
        sa.Column("telegram_user_id", sa.UUID(), nullable=False),
        sa.Column(
            "status",
            postgresql.ENUM(
                "PENDING",
                "SUCCESS",
                "FAILED",
                "SKIPPED",
                name="deliverystatus",
                create_type=False,
            ),
            nullable=False,
        ),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["broadcast_id"],
            ["broadcasts.id"],
            name=op.f("fk_broadcast_deliveries_broadcast_id_broadcasts"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["telegram_user_id"],
            ["telegram_users.id"],
            name=op.f("fk_broadcast_deliveries_telegram_user_id_telegram_users"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_broadcast_deliveries")),
    )
    op.create_table(
        "chats",
        sa.Column("bot_id", sa.UUID(), nullable=False),
        sa.Column("telegram_user_id", sa.UUID(), nullable=False),
        sa.Column(
            "status",
            postgresql.ENUM(
                "OPEN",
                "CLOSED",
                "BLOCKED",
                name="chatstatus",
                create_type=False,
            ),
            nullable=False,
        ),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["bot_id"], ["bots.id"], name=op.f("fk_chats_bot_id_bots")
        ),
        sa.ForeignKeyConstraint(
            ["telegram_user_id"],
            ["telegram_users.id"],
            name=op.f("fk_chats_telegram_user_id_telegram_users"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_chats")),
    )
    op.create_index(op.f("ix_chats_is_deleted"), "chats", ["is_deleted"], unique=False)
    op.create_table(
        "messages",
        sa.Column("chat_id", sa.UUID(), nullable=False),
        sa.Column(
            "sender_type",
            postgresql.ENUM(
                "USER",
                "BOT",
                "ADMIN",
                "SYSTEM",
                name="sendertype",
                create_type=False,
            ),
            nullable=False,
        ),
        sa.Column(
            "message_type",
            postgresql.ENUM(
                "TEXT",
                "MEDIA",
                "IMAGE",
                "VIDEO",
                "AUDIO",
                "DOCUMENT",
                "SYSTEM",
                name="messagetype",
                create_type=False,
            ),
            nullable=False,
        ),
        sa.Column("tg_message_id", sa.Integer(), nullable=True),
        sa.Column("content", sa.Text(), nullable=True),
        sa.Column(
            "metadata_info",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=False,
        ),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["chat_id"], ["chats.id"], name=op.f("fk_messages_chat_id_chats")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_messages")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("messages")
    op.drop_index(op.f("ix_chats_is_deleted"), table_name="chats")
    op.drop_table("chats")
    op.drop_table("broadcast_deliveries")
    op.drop_index(op.f("ix_telegram_users_is_deleted"), table_name="telegram_users")
    op.drop_index("idx_tg_user_bot", table_name="telegram_users")
    op.drop_table("telegram_users")
    op.drop_index(op.f("ix_broadcasts_is_deleted"), table_name="broadcasts")
    op.drop_table("broadcasts")
    op.drop_table("audit_logs")
    op.drop_table("admin_bot_roles")
    op.drop_table("workspace_members")
    op.drop_index(op.f("ix_bots_is_deleted"), table_name="bots")
    op.drop_table("bots")
    op.drop_table("workspaces")
    op.drop_index(
        "uq_users_username_not_deleted",
        table_name="users",
        postgresql_where=sa.text("is_deleted = false"),
    )
    op.drop_index(
        "uq_users_email_active_not_deleted",
        table_name="users",
        postgresql_where=sa.text("is_deleted = false"),
    )
    op.drop_index(op.f("ix_users_is_deleted"), table_name="users")
    op.drop_table("users")
    sa.Enum("ACTIVE", "DISABLED", "MAINTENANCE", name="botstatus").drop(op.get_bind())
    sa.Enum("ADMIN", "EDITOR", "SUPPORT", "VIEWER", name="botrole").drop(op.get_bind())
    sa.Enum("OPEN", "CLOSED", "BLOCKED", name="chatstatus").drop(op.get_bind())
    sa.Enum("USER", "BOT", "ADMIN", "SYSTEM", name="sendertype").drop(op.get_bind())
    sa.Enum(
        "TEXT",
        "MEDIA",
        "IMAGE",
        "VIDEO",
        "AUDIO",
        "DOCUMENT",
        "SYSTEM",
        name="messagetype",
    ).drop(op.get_bind())
    sa.Enum(
        "DRAFT",
        "SCHEDULED",
        "PROCESSING",
        "SENT",
        "FAILED",
        "CANCELLED",
        name="broadcaststatus",
    ).drop(op.get_bind())
    sa.Enum("PENDING", "SUCCESS", "FAILED", "SKIPPED", name="deliverystatus").drop(
        op.get_bind()
    )
    sa.Enum("OWNER", "MEMBER", name="workspacerole").drop(op.get_bind())
    # ### end Alembic commands ###
