"""remove redundant permission field

Revision ID: aee42dd2199f
Revises: 515e6154818b
Create Date: 2026-02-21 20:53:38.330219

"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "aee42dd2199f"
down_revision: str | None = "515e6154818b"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("admin_bot_roles", "permissions")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "admin_bot_roles",
        sa.Column(
            "permissions",
            postgresql.JSONB(astext_type=sa.Text()),
            autoincrement=False,
            nullable=False,
        ),
    )
    # ### end Alembic commands ###
