"""extended soft delete

Revision ID: c096e09e32e6
Revises: 9a0e3f8c57e6
Create Date: 2026-01-18 10:53:08.579055

"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "c096e09e32e6"
down_revision: str | None = "9a0e3f8c57e6"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "workspace_members",
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
    )
    op.add_column(
        "workspace_members",
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
    )
    op.create_index(
        op.f("ix_workspace_members_is_deleted"),
        "workspace_members",
        ["is_deleted"],
        unique=False,
    )
    op.add_column(
        "workspaces",
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
    )
    op.add_column("workspaces", sa.Column("is_deleted", sa.Boolean(), nullable=False))
    op.create_index(
        op.f("ix_workspaces_is_deleted"),
        "workspaces",
        ["is_deleted"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_workspaces_is_deleted"), table_name="workspaces")
    op.drop_column("workspaces", "is_deleted")
    op.drop_column("workspaces", "deleted_at")
    op.drop_index(
        op.f("ix_workspace_members_is_deleted"), table_name="workspace_members"
    )
    op.drop_column("workspace_members", "is_deleted")
    op.drop_column("workspace_members", "deleted_at")
    # ### end Alembic commands ###
