"""use telegram auth

Revision ID: d69ff11b09aa
Revises: da02a31de83d
Create Date: 2026-03-06 12:28:03.832080

"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "d69ff11b09aa"
down_revision: str | None = "da02a31de83d"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("telegram_id", sa.Integer(), nullable=False))
    op.add_column(
        "users",
        sa.Column("language_code", sa.String(length=10), nullable=True),
    )
    op.add_column(
        "users", sa.Column("photo_url", sa.String(length=1024), nullable=True)
    )
    op.alter_column(
        "users", "username", existing_type=sa.VARCHAR(length=60), nullable=True
    )
    op.alter_column(
        "users",
        "first_name",
        existing_type=sa.VARCHAR(length=50),
        nullable=True,
    )
    op.alter_column(
        "users",
        "last_name",
        existing_type=sa.VARCHAR(length=50),
        nullable=True,
    )
    op.drop_index(
        op.f("uq_users_email_active_not_deleted"),
        table_name="users",
        postgresql_where="(is_deleted = false)",
    )
    op.create_index(
        "uq_users_telegram_id_active_not_deleted",
        "users",
        ["telegram_id"],
        unique=True,
        postgresql_where=sa.text("is_deleted = false"),
    )
    op.drop_column("users", "email")
    op.drop_column("users", "password")
    op.drop_column("users", "is_verified")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column("is_verified", sa.BOOLEAN(), autoincrement=False, nullable=False),
    )
    op.add_column(
        "users",
        sa.Column(
            "password",
            sa.VARCHAR(length=255),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.add_column(
        "users",
        sa.Column(
            "email",
            sa.VARCHAR(length=255),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.drop_index(
        "uq_users_telegram_id_active_not_deleted",
        table_name="users",
        postgresql_where=sa.text("is_deleted = false"),
    )
    op.create_index(
        op.f("uq_users_email_active_not_deleted"),
        "users",
        ["email"],
        unique=True,
        postgresql_where="(is_deleted = false)",
    )
    op.alter_column(
        "users",
        "last_name",
        existing_type=sa.VARCHAR(length=50),
        nullable=False,
    )
    op.alter_column(
        "users",
        "first_name",
        existing_type=sa.VARCHAR(length=50),
        nullable=False,
    )
    op.alter_column(
        "users",
        "username",
        existing_type=sa.VARCHAR(length=60),
        nullable=False,
    )
    op.drop_column("users", "photo_url")
    op.drop_column("users", "language_code")
    op.drop_column("users", "telegram_id")
    # ### end Alembic commands ###
