"""add is_default workspace

Revision ID: f1d8f11de7e7
Revises: d69ff11b09aa
Create Date: 2026-03-11 17:09:35.361741

"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "f1d8f11de7e7"
down_revision: str | None = "d69ff11b09aa"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "workspace_members",
        sa.Column("is_default", sa.Boolean(), nullable=False),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("workspace_members", "is_default")
    # ### end Alembic commands ###
